package repository;

import model.*;

import java.util.*;
import java.util.concurrent.*;

public interface EventRepository {
    List<Organiser> ORGANISERS = Arrays.asList(
            new Organiser("Józef Kowalski"),
            new Organiser("Józefa Kowalska"),
            new Organiser("Andrzej Nowak"),
            new Organiser("Anna Nowak"),
            new Organiser("Piotr Piotrowicz")
    );
    List<Helper> HELPERS = Arrays.asList(
            new Helper("Marek Szuwarek"),
            new Helper("Mariola Szuwarek"),
            new Helper("Jędrzej Szuwarek"),
            new Helper("Karolina Talar"),
            new Helper("Józef Talar"),
            new Helper("Józefa Talar"),
            new Helper("Zbigniew Ścięgno"),
            new Helper("Zbigniewa Skurcz"),
            new Helper("Arkadiusz Skurcz"),
            new Helper("Adrianna Ziewańska")
    );
    List<Guest> GUESTS = Arrays.asList(
            new Guest("Jan", "Kowalski"),
            new Guest("Anna", "Nowak"),
            new Guest("Marek", "Wiśniewski"),
            new Guest("Ewa", "Dąbrowska"),
            new Guest("Kamil", "Lewandowski"),
            new Guest("Agnieszka", "Wójcik"),
            new Guest("Piotr", "Kamiński"),
            new Guest("Maria", "Kowalczyk"),
            new Guest("Tomasz", "Zieliński"),
            new Guest("Magdalena", "Szymańska"),
            new Guest("Adam", "Woźniak"),
            new Guest("Katarzyna", "Kozłowska"),
            new Guest("Michał", "Jankowski"),
            new Guest("Joanna", "Wojciechowska"),
            new Guest("Grzegorz", "Kwiatkowski"),
            new Guest("Beata", "Kaczmarek"),
            new Guest("Łukasz", "Mazur"),
            new Guest("Dorota", "Krawczyk"),
            new Guest("Robert", "Piotrowski"),
            new Guest("Kinga", "Grabowska")
    );

    default List<Event> getAll() {
        return Arrays.asList(
                new CocktailPartyEvent(100, getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS)),
                new WeddingEvent(new Cake(), getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS)),
                new ConferenceEvent(getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS)),
                new CocktailPartyEvent(100, getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS)),
                new WeddingEvent(new Cake(), getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS)),
                new ConferenceEvent(getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS)),
                new CocktailPartyEvent(100, getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS)),
                new WeddingEvent(new Cake(), getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS)),
                new ConferenceEvent(getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(ORGANISERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS),
                        getRandomEmployee(HELPERS))
        );
    }

    default <E> E getRandomEmployee(List<E> employees) {
        return employees.get(ThreadLocalRandom.current().nextInt(employees.size()));
    }
}
